animals = ['bear', 'python', 'peacock', 'kangaroo', 'whale', 'platypus']

print "the animal at 1 is %s" %animals[0]
print "the third (3rd) animal %s" %animals[2]
print "the first (1st) animal  is %s" %animals[0]
print "the animal at 3 is %s" %animals[2]
print "the 5th animal is %s" % animals[4]
print "the animal at 2 is %s" %animals[1]
print "the 6th animal is %s"  %animals[5]
print "the 4th animal is %s" %animals[3]
